# dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_example?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&serverTimezone=Asia/Shanghai&&allowPublicKeyRetrieval=true
    username: root
    password: ea8dc0d1fe7e4073ad0296ea2eacc651
    druid:
      name: localhost
      max-active: 20
      min-idle: 5
      initial-size: 20
      #      connect-properties:
      #        config.decrypt: false
      #        config.decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAITb2QEPY7OBzr6mxAIKMFjzTTUFgcqmMiq+jS4ilbvpAa3s0QqTexoPEuMoOrmIrJVJoIGKUMnuo6pPF6BR2SECAwEAAQ==
      stat-view-servlet:
        login-username: admin
        login-password: admin123

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    database: 6

#xxl:
#  job:
#    adminAddresses: http://127.0.0.1:8080/xxl-job-admin
#    appName: tao-space
#    port: 20771
#    logPath: D:/log/tao/log
#    accessToken: 123456

#auth:
#  #秘钥
#  secret: c92d3c9d1bc440c59c9bcdff52a986bb
#  #失效时间单位秒
#  expires: 86400

mybatis-plus:
  mapper-locations: classpath:mybatis/default/*.xml
  # 控制台打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
